BabuDB/Java/Replication: fixed an issue that might have caused NoClassDefFoundErrors;
git-svn-id: https://babudb.googlecode.com/svn/trunk@425 d4c7dd96-b7b2-11dd-893d-d98698f66bbf